CREATE TABLE `profissoes` (
  `id` int(11) NOT NULL AUTO_INCREMENT, -- int(11) MySQL / integer para  Postgre
  `nome` varchar(50) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;

CREATE INDEX idx_nome ON profissoes (nome);


INSERT INTO `profissoes` (`nome`)
VALUES 
  ('Desenvolvedor de Software'),
  ('Engenheiro de Dados'),
  ('Arquiteto de Sistemas'),
  ('Analista de Banco de Dados'),
  ('Especialista em Segurança da Informação'),
  ('Administrador de Redes'),
  ('Cientista de Dados'),
  ('Engenheiro de Machine Learning'),
  ('Desenvolvedor Full Stack'),
  ('Gerente de Projetos de TI'),
  ('Analista de Sistemas'),
  ('Consultor de TI'),
  ('Engenheiro de Software'),
  ('Desenvolvedor Front-End'),
  ('Desenvolvedor Back-End'),
  ('Desenvolvedor Mobile'),
  ('Analista de Suporte Técnico'),
  ('Analista de Qualidade de Software'),
  ('Engenheiro de Redes'),
  ('Gerente de TI'),
  ('Administrador de Banco de Dados'),
  ('Especialista em Big Data'),
  ('Engenheiro de DevOps'),
  ('Arquiteto de Soluções'),
  ('Desenvolvedor de Jogos'),
  ('Engenheiro de Testes de Software'),
  ('Especialista em Cloud Computing'),
  ('Analista de Segurança da Informação'),
  ('Analista de Business Intelligence'),
  ('Analista de Redes'),
  ('Desenvolvedor de Inteligência Artificial'),
  ('Engenheiro de Sistemas'),
  ('Analista de Requisitos'),
  ('Desenvolvedor de Python'),
  ('Desenvolvedor de Java'),
  ('Desenvolvedor de C#'),
  ('Desenvolvedor de Ruby'),
  ('Desenvolvedor de PHP'),
  ('Desenvolvedor de JavaScript'),
  ('Desenvolvedor de C++'),
  ('Desenvolvedor de Swift'),
  ('Desenvolvedor de Kotlin'),
  ('Desenvolvedor de TypeScript'),
  ('Desenvolvedor de Go'),
  ('Desenvolvedor de Rust'),
  ('Desenvolvedor de Scala'),
  ('Desenvolvedor de Perl'),
  ('Desenvolvedor de Objective-C'),
  ('Desenvolvedor de R'),
  ('Desenvolvedor de Lua'),
  ('Desenvolvedor de SQL'),
  ('Desenvolvedor de HTML'),
  ('Desenvolvedor de CSS'),
  ('Desenvolvedor de Shell Script'),
  ('Desenvolvedor de MATLAB'),
  ('Desenvolvedor de Assembly'),
  ('Desenvolvedor de Lisp'),
  ('Desenvolvedor de Cobol'),
  ('Desenvolvedor de Fortran'),
  ('Desenvolvedor de Pascal'),
  ('Desenvolvedor de Delphi'),
  ('Desenvolvedor de Visual Basic'),
  ('Desenvolvedor de Racket'),
  ('Desenvolvedor de Erlang'),
  ('Desenvolvedor de Haskell'),
  ('Desenvolvedor de Prolog'),
  ('Desenvolvedor de Ada'),
  ('Desenvolvedor de Groovy'),
  ('Desenvolvedor de PL/SQL'),
  ('Desenvolvedor de Lua'),
  ('Desenvolvedor de TypeScript'),
  ('Desenvolvedor de Go'),
  ('Desenvolvedor de Rust'),
  ('Desenvolvedor de Scala'),
  ('Desenvolvedor de Perl'),
  ('Desenvolvedor de Objective-C'),
  ('Desenvolvedor de R'),
  ('Desenvolvedor de Lua'),
  ('Desenvolvedor de SQL'),
  ('Desenvolvedor de HTML'),
  ('Desenvolvedor de CSS'),
  ('Desenvolvedor de Shell Script'),
  ('Desenvolvedor de MATLAB'),
  ('Desenvolvedor de Lisp'),
  ('Desenvolvedor de Cobol'),
  ('Desenvolvedor de Fortran'),
  ('Desenvolvedor de Pascal'),
  ('Desenvolvedor de Delphi'),
  ('Desenvolvedor de Visual Basic'),
  ('Desenvolvedor de Prolog'),
  ('Desenvolvedor de PL/SQL'),
  ('Analista de Testes'),
  ('Especialista em QA (Garantia de Qualidade)'),
  ('Engenheiro de Sistemas Operacionais'),
  ('Administrador de Banco de Dados Oracle'),
  ('Engenheiro de Redes Cisco'),
  ('Consultor de Implantação de Sistemas'),
  ('Gerente de Infraestrutura de TI'),
  ('Especialista em Virtualização'),
  ('Analista de Segurança de Redes'),
  ('Arquiteto de Soluções Cloud'),
  ('Engenheiro de Redes sem Fio'),
  ('Analista de Dados'),
  ('Especialista em Business Intelligence'),
  ('Arquiteto de Informação'),
  ('Engenheiro de Automação de Processos'),
  ('Consultor de E-commerce'),
  ('Analista de Suporte ERP'),
  ('Especialista em Internet das Coisas (IoT)'),
  ('Engenheiro de Redes Sociais'),
  ('Analista de Redes Sociais'),
  ('Gerente de Projetos de Implantação de Sistemas'),
  ('Especialista em Análise de Vulnerabilidades'),
  ('Analista de UX/UI'),
  ('Engenheiro de Redes VoIP'),
  ('Administrador de Sistemas Linux'),
  ('Especialista em Blockchain'),
  ('Arquiteto de Segurança'),
  ('Analista de Infraestrutura de TI'),
  ('Engenheiro de Datacenter'),
  ('Analista de Suporte Técnico de Redes'),
  ('Especialista em Computação Forense'),
  ('Consultor de SAP'),
  ('Engenheiro de Redes MPLS'),
  ('Administrador de Sistemas Windows Server'),
  ('Especialista em Gestão de Projetos de TI'),
  ('Analista de Suporte Técnico de Aplicativos'),
  ('Arquiteto de Sistemas ERP'),
  ('Engenheiro de Redes SDN'),
  ('Analista de BI (Inteligência de Negócios)'),
  ('Especialista em Automação de Testes'),
  ('Consultor de Segurança da Informação'),
  ('Engenheiro de Redes LAN/WAN'),
  ('Administrador de Sistemas Unix'),
  ('Especialista em Robótica'),
  ('Analista de Suporte Técnico de Banco de Dados'),
  ('Arquiteto de Integração de Sistemas'),
  ('Engenheiro de Redes 5G'),
  ('Analista de CRM'),
  ('Especialista em Data Science'),
  ('Consultor de Governança de TI'),
  ('Engenheiro de Redes IoT'),
  ('Administrador de Sistemas Mainframe'),
  ('Especialista em Realidade Virtual'),
  ('Analista de Suporte Técnico de ERP'),
  ('Arquiteto de Sistemas de Pagamento'),
  ('Engenheiro de Redes WAN'),
  ('Analista de E-commerce'),
  ('Especialista em Machine Learning'),
  ('Consultor de Transformação Digital'),
  ('Engenheiro de Redes VPN'),
  ('Administrador de Sistemas Cloud'),
  ('Especialista em Inteligência Artificial'),
  ('Analista de Suporte Técnico de Sistemas'),
  ('Arquiteto de Sistemas CRM'),
  ('Engenheiro de Redes Seguras'),
  ('Analista de CRM'),
  ('Especialista em Data Science'),
  ('Consultor de Governança de TI'),
  ('Engenheiro de Redes IoT'),
  ('Administrador de Sistemas Mainframe'),
  ('Especialista em Realidade Virtual'),
  ('Analista de Suporte Técnico de ERP'),
  ('Arquiteto de Sistemas de Pagamento'),
  ('Engenheiro de Redes WAN'),
  ('Analista de E-commerce'),
  ('Especialista em Machine Learning'),
  ('Consultor de Transformação Digital'),
  ('Engenheiro de Redes VPN'),
  ('Administrador de Sistemas Cloud'),
  ('Especialista em Inteligência Artificial'),
  ('Analista de Suporte Técnico de Sistemas');

